name: "Godot Setup"
description: "Setup Godot to run in graphical mode (i.e. non-headless) on Linux, Windows, or macOS."
branding:
  icon: "monitor"
  color: "blue"
inputs:
  version:
    description: "Godot version to use"
    required: true
    default: "4.3-stable"
  arch:
    description: "Target architecture (x86_64, arm64, x86_32, arm32). Auto-detected if not specified."
    required: false
  mono:
    description: "Use the Mono build"
    required: false
    default: false
  alias:
    description: "Name of the Godot executable that will be added to PATH"
    required: false
    default: "godot"
  cache:
    description: "Whether to save/restore Godot download (and mesa-dist-win on Windows runners) to/from cache"
    required: false
    default: true
  export-templates:
    description: "Whether to download export templates"
    required: false
    default: false
  github-token:
    descripton: "GitHub token. Used to avoid API rate limits when downloading the mesa-dist-win release from GitHub on Windows runners. Defaults to secrets.GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "index.js"
